# Generated by Django 3.1.7 on 2021-03-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('DEV', 'DEV'), ('USER', 'USER')], default='ADMIN', max_length=20),
        ),
    ]
