# Generated by Django 3.1.7 on 2021-04-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210316_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
