# Generated by Django 3.1.7 on 2021-03-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='user_id',
            new_name='user',
        ),
    ]
