# Generated by Django 3.1.7 on 2021-03-01 18:04

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210301_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='commit_count',
            field=models.IntegerField(default=app.models.Commit.default_commit_count),
        ),
    ]
