# Generated by Django 3.1.7 on 2021-04-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commit',
        ),
    ]
