# Generated by Django 3.1.7 on 2021-04-01 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='leaderboards_participated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
