# Generated by Django 3.1.7 on 2021-03-13 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_commitrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitrecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
