# Generated by Django 3.1.7 on 2021-03-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_commitrecord_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
