# Generated by Django 3.1.7 on 2021-04-01 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20210401_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='leaderboards_participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
