# Generated by Django 3.1.7 on 2021-03-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_leaderboard_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitrecord',
            name='leaderboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.leaderboard'),
        ),
    ]
