# Generated by Django 3.1.7 on 2021-04-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210401_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
