# Generated by Django 3.1.7 on 2021-04-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_leaderboard_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='results',
        ),
        migrations.AddField(
            model_name='result',
            name='leaderboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app.leaderboard'),
        ),
    ]
