# Generated by Django 3.1.7 on 2021-04-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210403_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='nodeid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commit',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
