# Generated by Django 3.1.7 on 2021-04-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_leaderboard_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
